#!/bin/bash
# ===========================================================================
# Appends the IIQ tuning to the postgresql.conf generated by the entrypoint.
#
# Runs as the first script in /docker-entrypoint-initdb.d (prefix 00),
# i.e. BEFORE the schema DDL and while the temporary server is running.
#
# Background: "include_dir" cannot be passed via "postgres -c" - it is
# valid only inside a configuration file. Appending is the most robust
# way that avoids replacing the image-generated configuration.
# ===========================================================================
set -euo pipefail

TUNING_SRC="/opt/iiq/postgresql.tuning.conf"
PG_CONF="${PGDATA}/postgresql.conf"

if [ ! -f "${TUNING_SRC}" ]; then
    echo "[iiq-tuning] No tuning file found - skipped."
    exit 0
fi

# Idempotent: do not append twice on a re-run.
if grep -q "IIQ-TUNING-BEGIN" "${PG_CONF}"; then
    echo "[iiq-tuning] Tuning already active."
    exit 0
fi

echo "[iiq-tuning] Appending IdentityIQ tuning to ${PG_CONF}."
{
    echo ""
    echo "# --- IIQ-TUNING-BEGIN (appended automatically) ---"
    cat "${TUNING_SRC}"
    echo "# --- IIQ-TUNING-END ---"
} >> "${PG_CONF}"

# Deliberately NO "pg_ctl reload" here.
#
# Parameters like max_connections, shared_buffers and wal_buffers can
# only be changed at server start. A reload during initialization would
# write messages like
#   "parameter ... cannot be changed without restarting the server"
#   "configuration file ... contains errors"
# to the log - looks like an error, is not one.
#
# The Postgres image's entrypoint shuts down the temporary init server
# anyway and starts the real one. The full configuration takes effect
# then at the latest.
echo "[iiq-tuning] Done - effective from the next server start."
