#!/usr/bin/env python3
# ===========================================================================
# SCIM 2.0 server as target system for the SCIM2Connector
# ===========================================================================
# Implements the part of RFC 7643/7644 that IdentityIQ's SCIM 2.0
# connector actually uses:
#
#   GET          /ServiceProviderConfig        capabilities (no token needed;
#                                              doubles as the health check)
#   GET          /ResourceTypes[/{id}]
#   GET          /Schemas[/{urn}]
#   GET, POST    /Users                        list (filter, paging), create
#   GET, PUT,
#   PATCH, DELETE /Users/{id}
#   GET, POST    /Groups
#   GET, PUT,
#   PATCH, DELETE /Groups/{id}
#
# Why not a third-party SCIM server: the one used before (harrykodden/scim)
# stores group membership only on the Group resource and never derives the
# read-only "groups" attribute of a User. The connector aggregates account
# entitlements from exactly that attribute (groups[*].value), so every role
# with SCIM entitlements would have been re-provisioned on every refresh and
# never detected. Here "groups" is computed from Groups.members on every
# read, as RFC 7643 section 4.1.2 describes it.
#
# Deliberately no framework, like the REST mock: the standard library is
# enough, the image stays at ~50 MB and there is no dependency to pin.
#
# Data lives in memory and is seeded at start from /data/seed
# (scim-users.json, scim-groups.json, both generated by
# scripts/generate-testdata.py). A restart therefore brings the seed
# back on its own; nothing has to be replayed by hand.
#
# Authentication: "Authorization: Bearer <API_KEY>" on every resource
# endpoint. That matches authType="oauthBearer" in the application.
# ===========================================================================
import json
import os
import re
import threading
import uuid
from datetime import datetime, timezone
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

API_KEY = os.environ.get("API_KEY", "secret")
PORT = int(os.environ.get("PORT", "8000"))
SEED_DIR = Path(os.environ.get("SEED_DIR", "/data/seed"))
# Base URL used in meta.location and $ref. The connector does not follow
# them; they only have to be well-formed.
BASE_URL = os.environ.get("BASE_URL", f"http://scim:{PORT}")

SCHEMA_USER = "urn:ietf:params:scim:schemas:core:2.0:User"
SCHEMA_GROUP = "urn:ietf:params:scim:schemas:core:2.0:Group"
SCHEMA_LIST = "urn:ietf:params:scim:api:messages:2.0:ListResponse"
SCHEMA_PATCH = "urn:ietf:params:scim:api:messages:2.0:PatchOp"
SCHEMA_ERROR = "urn:ietf:params:scim:api:messages:2.0:Error"
SCHEMA_SPC = "urn:ietf:params:scim:schemas:core:2.0:ServiceProviderConfig"
SCHEMA_RT = "urn:ietf:params:scim:schemas:core:2.0:ResourceType"
SCHEMA_SCHEMA = "urn:ietf:params:scim:schemas:core:2.0:Schema"

# Attributes that are multi-valued complex lists on the resources served
# here. PATCH treats them as lists (append / remove elements), everything
# else as a scalar or a sub-object.
MULTI_VALUED = {"emails", "members", "groups", "phoneNumbers", "addresses"}
# Attributes the client may not write; they are derived or server-owned.
READ_ONLY = {"id", "meta", "groups", "schemas"}

_lock = threading.Lock()
_users: dict[str, dict] = {}
_groups: dict[str, dict] = {}


def now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def stable_id(kind: str, key: str) -> str:
    """
    Deterministic id, so a container restart (or a test-data regeneration
    with the same seed) yields the same ids and role definitions that
    reference group ids stay valid.
    """
    return str(uuid.uuid5(uuid.NAMESPACE_URL, f"scim:{kind}:{key}"))


class ScimError(Exception):
    def __init__(self, status: int, detail: str, scim_type: str | None = None):
        super().__init__(detail)
        self.status = status
        self.detail = detail
        self.scim_type = scim_type


# ---------------------------------------------------------------------------
# Filter parsing (RFC 7644 section 3.4.2.2)
#
# Grammar covered:  expr := term (('and'|'or') term)*
#                   term := 'not'? '(' expr ')'
#                         | attrPath '[' expr ']'          (value filter)
#                         | attrPath 'pr'
#                         | attrPath op value
# Enough for what the connector and this landscape send:
#   externalId eq "1031", userName eq "x", members[value eq "<id>"].
# ---------------------------------------------------------------------------
_TOKEN = re.compile(
    r'\s*(?:(?P<lp>\()|(?P<rp>\))|(?P<lb>\[)|(?P<rb>\])'
    r'|(?P<str>"(?:[^"\\]|\\.)*")|(?P<word>[A-Za-z0-9_.:$\-]+))')


def _tokenize(text: str) -> list[tuple[str, str]]:
    pos, out = 0, []
    while pos < len(text):
        m = _TOKEN.match(text, pos)
        if not m or m.end() == pos:
            raise ScimError(400, f"invalid filter near: {text[pos:pos + 20]}", "invalidFilter")
        pos = m.end()
        kind = m.lastgroup
        if kind:
            out.append((kind, m.group(kind)))
    return out


class _Parser:
    def __init__(self, tokens: list[tuple[str, str]]):
        self.t = tokens
        self.i = 0

    def peek(self):
        return self.t[self.i] if self.i < len(self.t) else (None, None)

    def take(self):
        tok = self.peek()
        self.i += 1
        return tok

    def parse(self):
        node = self.expr()
        if self.peek()[0] is not None:
            raise ScimError(400, "unexpected token in filter", "invalidFilter")
        return node

    def expr(self):
        left = self.term()
        while self.peek()[0] == "word" and self.peek()[1].lower() in ("and", "or"):
            op = self.take()[1].lower()
            right = self.term()
            left = (op, left, right)
        return left

    def term(self):
        kind, val = self.peek()
        if kind == "word" and val.lower() == "not":
            self.take()
            return ("not", self.term())
        if kind == "lp":
            self.take()
            node = self.expr()
            if self.take()[0] != "rp":
                raise ScimError(400, "missing ) in filter", "invalidFilter")
            return node
        if kind != "word":
            raise ScimError(400, "attribute expected in filter", "invalidFilter")
        attr = self.take()[1]
        kind, val = self.peek()
        if kind == "lb":
            self.take()
            sub = self.expr()
            if self.take()[0] != "rb":
                raise ScimError(400, "missing ] in filter", "invalidFilter")
            return ("any", attr, sub)
        if kind == "word" and val.lower() == "pr":
            self.take()
            return ("pr", attr)
        if kind != "word":
            raise ScimError(400, "operator expected in filter", "invalidFilter")
        op = self.take()[1].lower()
        kind, val = self.take()
        if kind == "str":
            value = json.loads(val)
        elif kind == "word":
            value = {"true": True, "false": False, "null": None}.get(val.lower(), val)
        else:
            raise ScimError(400, "value expected in filter", "invalidFilter")
        return ("cmp", attr, op, value)


def parse_filter(text: str | None):
    if not text:
        return None
    return _Parser(_tokenize(text)).parse()


def _lookup(resource: dict, path: str):
    """Resolves a dotted attribute path; lists yield lists of sub-values."""
    # A schema-qualified path (urn:...:User:userName) reduces to its tail.
    if path.startswith("urn:"):
        path = path.rsplit(":", 1)[-1]
    cur = resource
    for part in path.split("."):
        if isinstance(cur, list):
            cur = [c.get(part) if isinstance(c, dict) else None for c in cur]
            cur = [c for c in cur if c is not None]
        elif isinstance(cur, dict):
            key = next((k for k in cur if k.lower() == part.lower()), None)
            cur = cur.get(key) if key else None
        else:
            return None
        if cur is None:
            return None
    return cur


def _compare(actual, op: str, expected) -> bool:
    if isinstance(actual, list):
        return any(_compare(a, op, expected) for a in actual)
    if isinstance(actual, dict):
        actual = actual.get("value")
    if actual is None:
        return op == "ne"
    if isinstance(actual, bool) or isinstance(expected, bool):
        a, e = str(actual).lower(), str(expected).lower()
    else:
        a, e = str(actual).lower(), str(expected).lower()
    return {
        "eq": a == e, "ne": a != e, "co": e in a, "sw": a.startswith(e),
        "ew": a.endswith(e), "gt": a > e, "ge": a >= e, "lt": a < e, "le": a <= e,
    }.get(op, False)


def matches(resource: dict, node) -> bool:
    if node is None:
        return True
    kind = node[0]
    if kind == "and":
        return matches(resource, node[1]) and matches(resource, node[2])
    if kind == "or":
        return matches(resource, node[1]) or matches(resource, node[2])
    if kind == "not":
        return not matches(resource, node[1])
    if kind == "pr":
        return _lookup(resource, node[1]) not in (None, [], "")
    if kind == "any":
        values = _lookup(resource, node[1])
        if not isinstance(values, list):
            values = [values] if values is not None else []
        return any(isinstance(v, dict) and matches(v, node[2]) for v in values)
    if kind == "cmp":
        return _compare(_lookup(resource, node[1]), node[2], node[3])
    return False


# ---------------------------------------------------------------------------
# Resource helpers
# ---------------------------------------------------------------------------
def unflatten(body: dict) -> dict:
    """
    Accepts both the nested form ({"name": {"givenName": ...}}) and the
    flattened form some clients send ({"name.givenName": ...},
    {"emails.value": ...}). Multi-valued paths become one-element lists.
    """
    out: dict = {}
    for key, value in body.items():
        if "." not in key or key.startswith("urn:"):
            out[key] = value
            continue
        head, tail = key.split(".", 1)
        if head in MULTI_VALUED:
            lst = out.setdefault(head, [])
            if not lst:
                lst.append({})
            lst[0][tail] = value
        else:
            out.setdefault(head, {})[tail] = value
    return out


def coerce_bool(value):
    if isinstance(value, str):
        return value.strip().lower() == "true"
    return bool(value)


def user_out(user: dict) -> dict:
    """Output view: adds the derived, read-only "groups" attribute."""
    res = dict(user)
    res["groups"] = [
        {"value": g["id"], "display": g["displayName"],
         "$ref": f"{BASE_URL}/Groups/{g['id']}"}
        for g in _groups.values()
        if any(m.get("value") == user["id"] for m in g.get("members", []))
    ]
    return res


def group_out(group: dict) -> dict:
    res = dict(group)
    members = []
    for m in group.get("members", []):
        u = _users.get(m.get("value"))
        members.append({"value": m["value"],
                        "display": u.get("userName") if u else m.get("display"),
                        "$ref": f"{BASE_URL}/Users/{m['value']}"})
    res["members"] = members
    return res


def meta(resource_type: str, rid: str, created: str | None = None) -> dict:
    stamp = now()
    return {"resourceType": resource_type, "created": created or stamp,
            "lastModified": stamp,
            "location": f"{BASE_URL}/{resource_type}s/{rid}"}


def validate_user(user: dict, own_id: str | None) -> None:
    if not user.get("userName"):
        raise ScimError(400, "userName is required", "invalidValue")
    for other in _users.values():
        if other["id"] == own_id:
            continue
        if other.get("userName", "").lower() == user["userName"].lower():
            raise ScimError(409, f"userName {user['userName']} already exists", "uniqueness")
        if user.get("externalId") and other.get("externalId") == user["externalId"]:
            raise ScimError(409, f"externalId {user['externalId']} already exists", "uniqueness")


def validate_group(group: dict, own_id: str | None) -> None:
    if not group.get("displayName"):
        raise ScimError(400, "displayName is required", "invalidValue")
    for other in _groups.values():
        if other["id"] != own_id and other["displayName"].lower() == group["displayName"].lower():
            raise ScimError(409, f"group {group['displayName']} already exists", "uniqueness")
    for m in group.get("members", []):
        if not isinstance(m, dict) or m.get("value") not in _users:
            raise ScimError(400, f"unknown member {m}", "invalidValue")


def normalize_user(body: dict, existing: dict | None) -> dict:
    body = unflatten(body)
    user = {k: v for k, v in body.items() if k not in READ_ONLY}
    user["schemas"] = [SCHEMA_USER]
    if "active" in user:
        user["active"] = coerce_bool(user["active"])
    else:
        user["active"] = existing.get("active", True) if existing else True
    return user


def normalize_group(body: dict) -> dict:
    body = unflatten(body)
    group = {k: v for k, v in body.items() if k not in READ_ONLY}
    group["schemas"] = [SCHEMA_GROUP]
    members = []
    for m in group.get("members") or []:
        if isinstance(m, str):
            m = {"value": m}
        if m.get("value") and m["value"] not in [x["value"] for x in members]:
            members.append({"value": m["value"]})
    group["members"] = members
    return group


# ---------------------------------------------------------------------------
# PATCH (RFC 7644 section 3.5.2)
# ---------------------------------------------------------------------------
_PATH = re.compile(r'^(?P<attr>[A-Za-z0-9_:.$\-]+?)(?:\[(?P<filter>[^\]]+)\])?(?:\.(?P<sub>[A-Za-z0-9_$]+))?$')


def apply_patch(resource: dict, operations: list) -> dict:
    res = json.loads(json.dumps(resource))
    for op in operations:
        if not isinstance(op, dict):
            raise ScimError(400, "operation must be an object", "invalidValue")
        kind = str(op.get("op", "")).lower()
        path = op.get("path")
        value = op.get("value")
        if kind not in ("add", "replace", "remove"):
            raise ScimError(400, f"unsupported op {kind}", "invalidValue")

        if not path:
            if kind == "remove":
                raise ScimError(400, "remove needs a path", "noTarget")
            if not isinstance(value, dict):
                raise ScimError(400, "value must be an object without a path", "invalidValue")
            for k, v in unflatten(value).items():
                if k in READ_ONLY:
                    continue
                if k in MULTI_VALUED and kind == "add":
                    _add_members(res, k, v)
                else:
                    res[k] = v
            continue

        m = _PATH.match(path)
        if not m:
            raise ScimError(400, f"unsupported path {path}", "invalidPath")
        attr, flt, sub = m.group("attr"), m.group("filter"), m.group("sub")
        if attr.startswith("urn:"):
            attr = attr.rsplit(":", 1)[-1]
        if attr in READ_ONLY:
            raise ScimError(400, f"{attr} is read-only", "mutability")

        if attr in MULTI_VALUED:
            lst = res.setdefault(attr, [])
            if flt:
                node = parse_filter(flt)
                hits = [x for x in lst if isinstance(x, dict) and matches(x, node)]
                if kind == "remove":
                    res[attr] = [x for x in lst if x not in hits]
                elif sub:
                    for x in hits:
                        x[sub] = value
                else:
                    for x in hits:
                        x.update(value if isinstance(value, dict) else {"value": value})
            elif kind == "remove":
                if value:
                    drop = {v.get("value") if isinstance(v, dict) else v
                            for v in (value if isinstance(value, list) else [value])}
                    res[attr] = [x for x in lst if x.get("value") not in drop]
                else:
                    res[attr] = []
            elif kind == "replace":
                res[attr] = value if isinstance(value, list) else [value]
            else:
                _add_members(res, attr, value)
        elif "." in attr or sub:
            head, tail = (attr.split(".", 1) if "." in attr else (attr, sub))
            if kind == "remove":
                res.get(head, {}).pop(tail, None)
            else:
                res.setdefault(head, {})[tail] = value
        else:
            if kind == "remove":
                res.pop(attr, None)
            else:
                res[attr] = value
    if "active" in res:
        res["active"] = coerce_bool(res["active"])
    return res


def _add_members(res: dict, attr: str, value) -> None:
    lst = res.setdefault(attr, [])
    items = value if isinstance(value, list) else [value]
    for item in items:
        if isinstance(item, str):
            item = {"value": item}
        if not isinstance(item, dict):
            continue
        if attr == "members" and item.get("value") not in _users:
            raise ScimError(400, f"unknown member {item.get('value')}", "invalidValue")
        if item.get("value") not in [x.get("value") for x in lst]:
            lst.append({k: v for k, v in item.items() if k != "$ref"})


# ---------------------------------------------------------------------------
# Discovery documents
# ---------------------------------------------------------------------------
def service_provider_config() -> dict:
    return {
        "schemas": [SCHEMA_SPC],
        "documentationUri": "https://www.rfc-editor.org/rfc/rfc7644",
        "patch": {"supported": True},
        "bulk": {"supported": False, "maxOperations": 0, "maxPayloadSize": 0},
        "filter": {"supported": True, "maxResults": 1000},
        "changePassword": {"supported": False},
        "sort": {"supported": False},
        "etag": {"supported": False},
        "authenticationSchemes": [{
            "type": "oauthbearertoken",
            "name": "OAuth Bearer Token",
            "description": "Static bearer token (API_KEY)",
            "primary": True,
        }],
        "meta": {"resourceType": "ServiceProviderConfig",
                 "location": f"{BASE_URL}/ServiceProviderConfig"},
    }


def _attr(name, typ="string", multi=False, required=False, mutability="readWrite",
          returned="default", uniqueness="none", sub=None, case_exact=False):
    a = {"name": name, "type": typ, "multiValued": multi, "description": name,
         "required": required, "caseExact": case_exact, "mutability": mutability,
         "returned": returned, "uniqueness": uniqueness}
    if sub:
        a["subAttributes"] = sub
    return a


def schemas() -> list[dict]:
    ref_sub = [_attr("value"), _attr("display", mutability="readOnly"),
               _attr("$ref", typ="reference")]
    return [
        {"schemas": [SCHEMA_SCHEMA], "id": SCHEMA_USER, "name": "User",
         "description": "User Account",
         "attributes": [
             _attr("userName", required=True, uniqueness="server"),
             _attr("externalId", uniqueness="server"),
             _attr("name", typ="complex", sub=[_attr("givenName"), _attr("familyName"),
                                               _attr("formatted")]),
             _attr("displayName"),
             _attr("emails", typ="complex", multi=True,
                   sub=[_attr("value"), _attr("type"), _attr("primary", typ="boolean")]),
             _attr("title"),
             _attr("active", typ="boolean"),
             _attr("groups", typ="complex", multi=True, mutability="readOnly", sub=ref_sub),
         ],
         "meta": {"resourceType": "Schema", "location": f"{BASE_URL}/Schemas/{SCHEMA_USER}"}},
        {"schemas": [SCHEMA_SCHEMA], "id": SCHEMA_GROUP, "name": "Group",
         "description": "Group",
         "attributes": [
             _attr("displayName", required=True, uniqueness="server"),
             _attr("members", typ="complex", multi=True, sub=ref_sub),
         ],
         "meta": {"resourceType": "Schema", "location": f"{BASE_URL}/Schemas/{SCHEMA_GROUP}"}},
    ]


def resource_types() -> list[dict]:
    return [
        {"schemas": [SCHEMA_RT], "id": "User", "name": "User", "endpoint": "/Users",
         "description": "User Account", "schema": SCHEMA_USER,
         "meta": {"resourceType": "ResourceType", "location": f"{BASE_URL}/ResourceTypes/User"}},
        {"schemas": [SCHEMA_RT], "id": "Group", "name": "Group", "endpoint": "/Groups",
         "description": "Group", "schema": SCHEMA_GROUP,
         "meta": {"resourceType": "ResourceType", "location": f"{BASE_URL}/ResourceTypes/Group"}},
    ]


def list_response(items: list[dict], query: dict) -> dict:
    try:
        start = max(1, int(query.get("startIndex", ["1"])[0]))
        count = int(query.get("count", [str(len(items) or 1)])[0])
    except ValueError:
        raise ScimError(400, "startIndex and count must be integers", "invalidValue")
    if count < 0:
        count = 0
    page = items[start - 1:start - 1 + count]
    return {"schemas": [SCHEMA_LIST], "totalResults": len(items),
            "itemsPerPage": len(page), "startIndex": start, "Resources": page}


# ---------------------------------------------------------------------------
# Seed
# ---------------------------------------------------------------------------
def load_seed() -> None:
    users_file = SEED_DIR / "scim-users.json"
    groups_file = SEED_DIR / "scim-groups.json"
    if not users_file.is_file():
        print(f"[scim] {users_file} not found - starting empty.")
        return
    try:
        users = json.loads(users_file.read_text(encoding="utf-8"))
        groups = json.loads(groups_file.read_text(encoding="utf-8")) if groups_file.is_file() else []
    except (OSError, ValueError) as e:
        print(f"[scim] seed not readable ({e}) - starting empty.")
        return

    by_external: dict[str, str] = {}
    for raw in users:
        user = normalize_user(raw, None)
        uid = raw.get("id") or stable_id("user", user.get("externalId") or user["userName"])
        user["id"] = uid
        user["meta"] = meta("User", uid)
        validate_user(user, uid)
        _users[uid] = user
        if user.get("externalId"):
            by_external[user["externalId"]] = uid

    unknown = 0
    for raw in groups:
        gid = raw.get("id") or stable_id("group", raw["displayName"])
        members = []
        for ext in raw.get("members", []):
            uid = by_external.get(str(ext))
            if uid:
                members.append({"value": uid})
            else:
                unknown += 1
        group = normalize_group({"displayName": raw["displayName"], "members": members})
        group["id"] = gid
        group["meta"] = meta("Group", gid)
        validate_group(group, gid)
        _groups[gid] = group
    print(f"[scim] seed: {len(_users)} users, {len(_groups)} groups"
          + (f", {unknown} member references without a seed user (ignored)" if unknown else ""))


# ---------------------------------------------------------------------------
# HTTP
# ---------------------------------------------------------------------------
class Handler(BaseHTTPRequestHandler):
    server_version = "scim-target/1.0"

    def log_message(self, fmt, *args):
        status = args[1] if len(args) > 1 else "-"
        print(f"[scim] {self.command} {self.path} -> {status}")

    # -- plumbing ---------------------------------------------------------
    def _send(self, status: int, payload=None, location: str | None = None) -> None:
        body = json.dumps(payload).encode() if payload is not None else b""
        self.send_response(status)
        if body:
            self.send_header("Content-Type", "application/scim+json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        if location:
            self.send_header("Location", location)
        self.end_headers()
        if body:
            self.wfile.write(body)

    def _error(self, status: int, detail: str, scim_type: str | None = None) -> None:
        payload = {"schemas": [SCHEMA_ERROR], "status": str(status), "detail": detail}
        if scim_type:
            payload["scimType"] = scim_type
        self._send(status, payload)

    def _authorized(self) -> bool:
        return self.headers.get("Authorization", "") == f"Bearer {API_KEY}"

    def _json(self):
        length = int(self.headers.get("Content-Length") or 0)
        raw = self.rfile.read(length) if length else b""
        if not raw.strip():
            return {}
        try:
            data = json.loads(raw)
        except ValueError:
            raise ScimError(400, "request body is not valid JSON", "invalidSyntax")
        if not isinstance(data, dict):
            raise ScimError(400, "request body must be a JSON object", "invalidSyntax")
        return data

    def _route(self):
        parsed = urlparse(self.path)
        path = unquote(parsed.path).rstrip("/")
        # Tolerate the common /scim/v2 prefix so the base URL can be either.
        if path.startswith("/scim/v2"):
            path = path[len("/scim/v2"):]
        return path, parse_qs(parsed.query)

    def _dispatch(self):
        path, query = self._route()
        try:
            if self.command == "GET" and path == "/ServiceProviderConfig":
                return self._send(200, service_provider_config())
            if not self._authorized():
                return self._error(401, "invalid or missing bearer token", "invalidCredentials")
            with _lock:
                self._handle(path, query)
        except ScimError as e:
            self._error(e.status, e.detail, e.scim_type)
        except Exception as e:  # noqa: BLE001 - a mock must never die on a request
            self._error(500, f"internal error: {e}")

    def _handle(self, path: str, query: dict) -> None:
        m = self.command
        if m == "GET" and path == "/Schemas":
            return self._send(200, list_response(schemas(), query))
        if m == "GET" and path.startswith("/Schemas/"):
            urn = path[len("/Schemas/"):]
            for s in schemas():
                if s["id"] == urn:
                    return self._send(200, s)
            raise ScimError(404, f"schema {urn} not found")
        if m == "GET" and path == "/ResourceTypes":
            return self._send(200, list_response(resource_types(), query))
        if m == "GET" and path.startswith("/ResourceTypes/"):
            rid = path[len("/ResourceTypes/"):]
            for r in resource_types():
                if r["id"] == rid:
                    return self._send(200, r)
            raise ScimError(404, f"resource type {rid} not found")

        for prefix, store, out, kind in (("/Users", _users, user_out, "User"),
                                         ("/Groups", _groups, group_out, "Group")):
            if path == prefix:
                if m == "GET":
                    node = parse_filter(query.get("filter", [None])[0])
                    items = [out(r) for r in store.values() if matches(out(r), node)]
                    return self._send(200, list_response(items, query))
                if m == "POST":
                    return self._create(kind, store, out)
                raise ScimError(405, f"{m} not allowed on {prefix}")
            if path.startswith(prefix + "/"):
                rid = path[len(prefix) + 1:]
                if rid not in store:
                    raise ScimError(404, f"{kind} {rid} not found")
                if m == "GET":
                    return self._send(200, out(store[rid]))
                if m == "PUT":
                    return self._replace(kind, store, out, rid)
                if m == "PATCH":
                    return self._patch(kind, store, out, rid)
                if m == "DELETE":
                    return self._delete(kind, store, rid)
                raise ScimError(405, f"{m} not allowed on {path}")
        raise ScimError(404, f"unknown path: {path}")

    # -- resource operations -----------------------------------------------
    def _create(self, kind: str, store: dict, out) -> None:
        body = self._json()
        if kind == "User":
            res = normalize_user(body, None)
            rid = stable_id("user", res.get("externalId") or res["userName"])
            if rid in store:
                rid = str(uuid.uuid4())
            res["id"] = rid
            validate_user(res, rid)
        else:
            res = normalize_group(body)
            rid = stable_id("group", res.get("displayName", ""))
            if rid in store:
                rid = str(uuid.uuid4())
            res["id"] = rid
            validate_group(res, rid)
        res["meta"] = meta(kind, rid)
        store[rid] = res
        self._send(201, out(res), res["meta"]["location"])

    def _replace(self, kind: str, store: dict, out, rid: str) -> None:
        body = self._json()
        old = store[rid]
        res = normalize_user(body, old) if kind == "User" else normalize_group(body)
        res["id"] = rid
        res["meta"] = meta(kind, rid, old["meta"]["created"])
        (validate_user if kind == "User" else validate_group)(res, rid)
        store[rid] = res
        self._send(200, out(res))

    def _patch(self, kind: str, store: dict, out, rid: str) -> None:
        body = self._json()
        if SCHEMA_PATCH not in (body.get("schemas") or []):
            raise ScimError(400, f"schemas must contain {SCHEMA_PATCH}", "invalidSyntax")
        ops = body.get("Operations")
        if not isinstance(ops, list) or not ops:
            raise ScimError(400, "Operations must be a non-empty list", "invalidSyntax")
        old = store[rid]
        res = apply_patch(old, ops)
        res["id"] = rid
        res["meta"] = meta(kind, rid, old["meta"]["created"])
        if kind == "Group":
            res = normalize_group(res) | {"id": rid, "meta": res["meta"]}
        (validate_user if kind == "User" else validate_group)(res, rid)
        store[rid] = res
        self._send(200, out(res))

    def _delete(self, kind: str, store: dict, rid: str) -> None:
        del store[rid]
        if kind == "User":
            for g in _groups.values():
                g["members"] = [x for x in g.get("members", []) if x.get("value") != rid]
        self._send(204)

    def do_GET(self):
        self._dispatch()

    def do_POST(self):
        self._dispatch()

    def do_PUT(self):
        self._dispatch()

    def do_PATCH(self):
        self._dispatch()

    def do_DELETE(self):
        self._dispatch()


def main() -> None:
    load_seed()
    server = ThreadingHTTPServer(("0.0.0.0", PORT), Handler)
    print(f"[scim] listening on :{PORT} - bearer token: set")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    main()
